### ISSUE TITLE
Switching between v3 and v4 page versions sends you to the root of the site instead of the v4 page

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [pivotal/docs-platform-automation#23] opened 2019-09-11 17:37 UTC
**Describe the bug**

When I land on v3 page and want to switch to v4 the page that is fetched is the default page instead of the v4 version of the page. For example if I'm looking at the download-product task reference and I want to see the v4 version of the page, I select the v4 drop down and I get directed to the root of the platform automation site. 

**To Reproduce**
1. Go to https://docs-pcf-staging.cfapps.io/platform-automation/v3.0/reference/task.html#configure-director
2. Click on "v4.0" at the top of the page
3. See that the landing page is https://docs-pcf-staging.cfapps.io/platform-automation/v4.0/ instead of https://docs-pcf-staging.cfapps.io/platform-automation/v4.0/tasks.html#configure-director

**Expected behavior**
I would expect that when I navigate to a v3 page then switch to its v4 counterpart that I stay on the same page topic, even if the page has moved location. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 69.0 (64-bit)

**Additional context**
n/a

**Comment by nbconklin** [comment] 2019-09-12 15:31
Hi Patrick - thanks for sharing. This was intentional behavior, not a bug. The content between versions varies widely in some cases (new pages etc) as we're always making improvements to the docs, along with the product changes that exist between versions. Could you tell me more about your workflow when you encountered this? Were you able to find the information you were seeking?

**Comment by patrick-huber-pivotal** [comment] 2019-09-12 16:11
When we come in from Google searches the index doesn't always point to the
latest version of the task. When you switch to v4 it sends you back to the
root and you have to go searching for the task again.

**Comment by nbconklin** [comment] 2019-09-16 18:04
Thanks for the info - we're continuing to make updates to our docs, including the left-hand navigation, to help improve the effectiveness of navigating and finding content in our docs. Our plan is to revisit implementing a change to address switching between versions at that time. TL'DR this a plan for later.

**Comment by nbconklin** [comment] 2019-09-23 16:55
we've captured this in our backlog, we'll circle back when we've completed the work. Closing for now.

**Closed as completed by nbconklin** 2019-09-23 16:55 UTC
Labels: accepted
